### ISSUE TITLE
There's now a 1.0.2 version available

### ISSUE THREAD

**Issue by zlogic** [webjars/angular-nvd3#2]
Would it be possible to update this to version 1.0.2 from upstream? https://github.com/krispo/angular-nvd3/releases/tag/v1.0.2

**Comment by itzg** [comment]
The latest version, 1.0.2, is available over in the [Bower section](http://www.webjars.org/bower). You'll just need to make a slight change to your dependency coordinates with a groupId of `org.webjars.bower`:

```
<dependency>
    <groupId>org.webjars.bower</groupId>
    <artifactId>angular-nvd3</artifactId>
    <version>1.0.2</version>
</dependency>
```

**Comment by zlogic** [comment]
OK, thanks!
